# -------------------------------------------------------------------------------------
# Permalinks Configuration
# See: https://gohugo.io/content-management/urls/#permalinks
# -------------------------------------------------------------------------------------

# posts = ":year/:month/:filename" 部署失败、有更改
posts = "posts/:slugorcontentbasename"
